### ISSUE TITLE
null

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/algorithms-issues#8]
This is another of the more general issues, this time about handling missing or empty values: `null`, `nil`, `None`, `NA`, `undefined`, `NULL`, and so on. They're different in different languages, and have different implications for different use cases. (This issue was triggered by discussion on https://github.com/disarm-platform/ui-raster-vector-summary-stats/issues/1)

As we're using JSON for the interchange, might be worth focusing on how this concept is handled in there. The [spec](http://www.json.org) is quite useful, and short story is that besides a values (string, number, boolean, array or objects), the only other value that can be represented is `null` - e.g. `{"value": null}`. So if we're handling that correctly on the function and UI sides, we should be ok.

It's possible that our functions are returning `{"value": "null"}` (a string of the word 'null' rather than the value `null`), or something similar - but that is probably a bug and we should address it in the function, rather than handling in the UI.

Would be great to hear from esp @HughSt and @ric70x7 about what problems we might run into if we're limiting ourselves to only using `null`.

**Comment by ric70x7** [comment]
We need to check this. It may be the case that python/r convert the null
value of json into their respective None/NA, and we don't have to worry.

A problem of not handling it correctly, say for example as a string 'null'
could make that a numeric vector with missing values is treated as a vector
of strings.

**Comment by onlyjsmith** [comment]
Think is valid, but not much we can do. 

Have added a draft entry into the updated DiSARM docs to cover this.

Closing.
